Pull Request for My Portfolio
DebbyMiressa/MyPortfolio pull request #1
Opened 2022-06-29 18:07 UTC by DebbyMiressa

This ('MyPortfolio') project is an implementation of the skeleton of a mobile version of a website. This request is intended to get approval on the 'mobile-version' branch which was based on the master branch initially.

2022-06-29 20:07 UTC, Ismailco requested changes
### Hi @DebbyMiressa,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 20:07 UTC, Ismailco commented on homepage.html
> +                </button>
- [ ] The image list should be wrapped in a `ul` tag, and each `img` should be inside `li`, also the images should be a link so you need to add an `a` tag inside the `li`

2022-06-29 20:07 UTC, Ismailco commented on homepage.html
> +    </div>
- [ ] Kindly add the right background image for this section and stick to the design as much as possible including the fonts, sizes, and margins

|Your design|Figma design|
|-|-|
|![Screenshot_20220629_205204](https://user-images.githubusercontent.com/25227022/176534997-42be9d9d-41c4-4dd3-a45c-2831b5321522.png)|![Screenshot_20220629_210335](https://user-images.githubusercontent.com/25227022/176535025-73484a6c-e995-4698-ae0e-f6766347c9fa.png)|

2022-06-30 08:15 UTC, topeogunleye approved these changes
### Hi @DebbyMiressa, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
 
> ## [Optional] suggestions:
> * [ ]  Please check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 08:46 UTC, merged